apiVersion: v1
kind: Pod
metadata:
  name: chatbot-pod
  labels:
    app: chatbot
spec:
  containers:
  - name: chatbot
    image: chatbot:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3000
