apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  type: NodePort
  selector:
    app: chatbot
  ports:
  - port: 3000 # listening port
    targetPort: 3000 # container port
    nodePort: 30000 # Service exposure port on each node (default = 30000-32767)
